// Texts of the ICATMAR Buoys app, one dictionary per language.
//
// Keys are read by main.js through t('key', { param: value }): `{param}` in a
// text is replaced by its value. A key missing from a language falls back to
// English, and a key missing from English shows the key itself - so a new
// text only has to be added to `en` to work everywhere, and translated later.
//
// Static texts in index.html are marked with data-i18n (textContent),
// data-i18n-html (innerHTML - for the texts that hold links), data-i18n-title
// and data-i18n-aria (attributes); main.js fills them in (see applyLanguage).
//
// What is NOT translated: buoy names and codes, institution names, sensor and
// instrument names, dataset ids and anything else that comes from the data
// sources as it is.
//
// DRAFT: the Catalan, Spanish and French texts are first versions, to be
// reviewed.

const en = {
  'app.title': 'ICATMAR Buoys',
  'loading': 'Loading…',
  // Loading screen: each data source as it is checked (see renderLoading)
  'loading.checking': 'Checking the data sources…',
  'loading.ready': 'Loading the latest data…',
  'loading.buoys': 'Buoys',
  'loading.forecasts': 'Forecasts',
  'loading.buoysFound': '{n} buoys',
  'loading.updatedAgo': 'updated {ago}',
  'loading.until': 'until {date}',
  'loading.unavailable': 'not available',
  'menu.open': 'Menu',
  'back': 'Back',
  'close': 'Close',

  // Top bar
  'update.loading': 'Loading…',
  'update.updating': 'Updating…',
  'update.nextLabel': 'Next update',
  'update.in': 'in {n} min',
  'update.inSoon': 'in <1 min',
  'update.refreshTitle': 'Tap to update now',

  // Columns and units
  'column.waves': 'Waves',
  'column.wind': 'Wind',
  'column.temperature': 'Water',
  'column.currents': 'Current',
  'header.buoy': 'Buoy',
  'header.time': 'Time',
  'header.timeTitle': 'Switch between local time and UTC',
  'header.changeUnit': 'Change unit',
  'unit.waveHeight': 'Wave height',
  'unit.windSpeed': 'Wind speed',
  'unit.temperature': 'Temperature',
  'unit.waterSpeed': 'Current speed',
  'unitPopup.aria': 'Choose a unit',
  'unitPopup.unit': 'Unit',
  'unitPopup.note': 'Units can also be changed in the menu',
  'timePopup.note': 'The time zone can also be changed in the menu',

  // Cells
  'cell.maxValue': 'Max: {value}',
  'cell.gustValue': 'Gust: {value}',
  'cell.forecastTitle': 'Model forecast - tap for details',
  'cell.measurementTitle': 'Measurement - tap for details',

  // Status
  'status.loading': 'loading…',
  'status.active': 'Active',
  'status.delayed': 'Delayed',
  'status.inactive': 'Inactive',
  'ago.none': 'no recent data',
  'ago.now': 'now',
  'ago.minutes': '{n} min ago',
  'ago.hours': '{n} h ago',
  'ago.days': '{n} days ago',

  // List and map
  'legend.forecastList': 'Model forecast (no measurement in the last {hours} h)',
  'legend.forecast': 'Model forecast',
  'legend.sources': 'Sources in the info panel',
  'map.button': 'Map',
  'map.title': 'Map',
  'map.subtitle': 'Tap a buoy to see its data',

  // Buoy view
  'buoy.interval': 'Interval between rows',
  'buoy.info': 'Buoy information',

  // Messages on a tapped cell
  'info.measurementAt': 'Measurement at {hour} ({from}–{to})',
  'info.buoy': 'Buoy: {name} ({id})',
  'info.sensor': 'Sensor: {sensors}',
  'info.variable': 'Variable: {variables}',
  'info.publishedAs': '{code}, published as {raw}',
  'info.computedFrom': '{code}, computed from {raw}',
  'info.source': 'Source: {sources}',
  'info.oneReading': '1 reading, at {time}',
  'info.readings': 'Average of {n} readings, {from}–{to}',
  'info.forecastAt': 'Model forecast at {hour} ({from}–{to})',
  'info.forecastFor': 'Model forecast for {time} - no measurement in the last {hours} h',
  'info.at': 'At: {name} ({id})',
  'info.model': 'Model: {model}',
  'info.by': 'By: {who}',
  'info.windsBy': '{model} winds by {institution}',
  'info.run': 'Run: {date} UTC ({ago})',
  'info.runPublished': 'Run: {date} UTC ({ago}, published {published})',
  'info.runNote': 'Run: {note}',
  'info.newRunEvery': 'new run every {n} h',
  'info.timeStep': 'time step {n} h',
  'info.sourceApi': "Source: {api}, through {provider}'s API ({host})",
  'info.sourceErddap': 'Source: {provider} ERDDAP ({host}), dataset {dataset}',
  'info.gridPoint': 'Grid point: {lat}° N, {lon}° E, {km} km from the buoy',
  'info.oneForecast': '1 forecast value, at {time}',
  'info.forecastValues': 'Average of {n} forecast values, {from}–{to}',
  'toast.forecast': 'This value is not a measurement: it comes from a model forecast.',
  'toast.forecastModel': 'This value is not a measurement: it comes from a model forecast ({model}).',

  // Info view
  'info.combined': 'A combined buoy',
  'info.buoyCard': 'Buoy',
  'info.institution': 'Institution',
  'info.position': 'Position',
  'info.depth': 'Depth',
  'info.distance': 'Distance to coast',
  'info.installed': 'Installed',
  'info.lastMeasurement': 'Last measurement',
  'info.sensors': 'Sensors',
  'info.license': 'License',
  'info.acknowledgement': 'Acknowledgement',
  'info.measurements': 'Measurements',
  'info.loading': 'Loading…',
  'info.noMeasurements': 'no measurements in the last {hours} h',
  'info.sensorShort': 'sensor {sensor}',
  'info.forecasts': 'Forecasts',
  'info.forecastsText': 'Where there are no measurements, the forecast is shown instead. AROME is preferred over ECMWF: '
    + 'its resolution is higher, but it only predicts about one or two days ahead, so ECMWF takes over afterwards. '
    + 'The same applies to the WAVEWATCH III wave forecasts, run by ICATMAR with AROME and with ECMWF winds. '
    + 'Where the Open-Meteo API has no wind forecast, the AROME and ECMWF winds those wave forecasts were run with are shown instead (without gusts). '
    + 'Forecasts also cover the past hours (hindcast), which is what is shown when a buoy has no data.',
  'info.loadingShort': 'loading…',
  'info.noForecast': 'no forecast available for this buoy',
  'info.fromTo': 'from {from} to {to}',
  'info.nearestSea': 'nearest sea point {km} km away',
  'info.institutions': 'Institutions',
  'join.and': ' and ',

  // Institutions' roles (info view)
  'role.buoy': '{name} buoy',
  'role.measurements': 'measurements ({host})',
  'role.model': '{model} ({product})',
  'role.api': 'forecast API ({product})',
  'role.forcing': '{model} forcing ({product})',
  'product.waves': 'wave forecast',
  'product.wind': 'wind forecast',
  'product.seaSurface': 'sea surface forecast',

  // Variables shown in the messages (standard codes, see data/variables.js)
  'variable.VHM0': 'Spectral significant wave height (Hm0)',
  'variable.WSPD': 'Horizontal wind speed',
  'variable.TEMP': 'Sea temperature',
  'variable.HCSP': 'Horizontal current speed',

  // Forecast models, by the catalogue's model id (AROME-HD and ECMWF-IFS025
  // keep their own names)
  'model.WW3-AROME': 'WAVEWATCH III forced by AROME',
  'model.WW3-ECMWF': 'WAVEWATCH III forced by ECMWF',
  'model.WW3-ECMWF-MED': 'WAVEWATCH III forced by ECMWF (Mediterranean)',
  'model.AROME-ERDDAP': 'AROME (WAVEWATCH III forcing)',
  'model.ECMWF-ERDDAP': 'ECMWF (WAVEWATCH III forcing)',
  'model.ROMS': 'ROMS sea surface forecast',

  // Virtual buoys (see the catalogue's 'Aggregated buoys')
  'aggregation.BCNS.description': 'The wave data comes from the Port of Barcelona buoy (PBCN, Puertos del Estado), and the wind, water temperature and currents from the Somorrostro buoy (SOMO, ICATMAR and ICM-CSIC). The data is mixed this way because of the different availability of the two buoys: PBCN measures waves but no wind, and SOMO measures wind, water temperature and currents but no waves.',
  'aggregation.BCNS.PBCN': 'Waves',
  'aggregation.BCNS.SOMO': 'Wind, water temperature and currents',

  // Menu
  'menu.title': 'Settings',
  'menu.language': 'Language',
  'menu.units': 'Units',
  'menu.time': 'Time',
  'menu.timezone': 'Time zone',
  'menu.local': 'Local',
  'menu.utc': 'UTC',
  'menu.about': 'About',
  'menu.funding': 'Funding',
  'about.developer': 'This app is in development and constant improvement (interface and data). '
    + 'If you experience any issues or have suggestions, please contact Gerard Llorach-Tó ({email}).',
  'about.code': 'The app is open source and the code can be found at {link}.',
  'about.disclaimer': 'The data presented in this app is for information purposes only. Although we strive to ensure its '
    + 'accuracy and reliability, we cannot guarantee that it is free of errors or interruptions, and it should not be used '
    + 'to make critical decisions without further verification.',
  'funding.text': 'This work is funded by the "Fons Europeu Marítim, de Pesca i d\'Aqüicultura (FEMPA)" under the Catalan '
    + 'Institute of Research for the Governance of the Sea (ICATMAR) - BOE-A-2023-25106 and by the framework of the project '
    + '“Severo Ochoa Center of Excellence” financially supported by ICM-CSIC (CEX2019-000928-S).',
  'logo.eu': 'Co-funded by the European Union',
};

const ca = {
  'app.title': 'Boies ICATMAR',
  'loading': 'Carregant…',
  'loading.checking': 'Comprovant les fonts de dades…',
  'loading.ready': 'Carregant les últimes dades…',
  'loading.buoys': 'Boies',
  'loading.forecasts': 'Prediccions',
  'loading.buoysFound': '{n} boies',
  'loading.updatedAgo': 'actualitzat {ago}',
  'loading.until': 'fins a {date}',
  'loading.unavailable': 'no disponible',
  'menu.open': 'Menú',
  'back': 'Enrere',
  'close': 'Tanca',

  'update.loading': 'Carregant…',
  'update.updating': 'Actualitzant…',
  'update.nextLabel': 'Actualització',
  'update.in': 'en {n} min',
  'update.inSoon': 'en <1 min',
  'update.refreshTitle': 'Toca per actualitzar ara',

  'column.waves': 'Onades',
  'column.wind': 'Vent',
  'column.temperature': 'Aigua',
  'column.currents': 'Corrent',
  'header.buoy': 'Boia',
  'header.time': 'Hora',
  'header.timeTitle': 'Canvia entre hora local i UTC',
  'header.changeUnit': 'Canvia la unitat',
  'unit.waveHeight': "Alçada d'onada",
  'unit.windSpeed': 'Velocitat del vent',
  'unit.temperature': 'Temperatura',
  'unit.waterSpeed': 'Velocitat del corrent',
  'unitPopup.aria': 'Tria una unitat',
  'unitPopup.unit': 'Unitat',
  'unitPopup.note': 'També pots canviar les unitats al menú',
  'timePopup.note': 'També pots canviar la zona horària al menú',

  'cell.maxValue': 'Màx: {value}',
  'cell.gustValue': 'Ratxa: {value}',
  'cell.forecastTitle': 'Predicció de model - toca per veure els detalls',
  'cell.measurementTitle': 'Mesura - toca per veure els detalls',

  'status.loading': 'carregant…',
  'status.active': 'Activa',
  'status.delayed': 'Amb retard',
  'status.inactive': 'Inactiva',
  'ago.none': 'sense dades recents',
  'ago.now': 'ara',
  'ago.minutes': 'fa {n} min',
  'ago.hours': 'fa {n} h',
  'ago.days': 'fa {n} dies',

  'legend.forecastList': 'Predicció de model (sense mesures en les últimes {hours} h)',
  'legend.forecast': 'Predicció de model',
  'legend.sources': "Fonts al panell d'informació",
  'map.button': 'Mapa',
  'map.title': 'Mapa',
  'map.subtitle': "Toca una boia per veure'n les dades",

  'buoy.interval': 'Interval entre files',
  'buoy.info': 'Informació de la boia',

  'info.measurementAt': 'Mesura de les {hour} ({from}–{to})',
  'info.buoy': 'Boia: {name} ({id})',
  'info.sensor': 'Sensor: {sensors}',
  'info.variable': 'Variable: {variables}',
  'info.publishedAs': '{code}, publicada com a {raw}',
  'info.computedFrom': '{code}, calculada a partir de {raw}',
  'info.source': 'Font: {sources}',
  'info.oneReading': '1 lectura, a les {time}',
  'info.readings': 'Mitjana de {n} lectures, {from}–{to}',
  'info.forecastAt': 'Predicció de model de les {hour} ({from}–{to})',
  'info.forecastFor': 'Predicció de model per a les {time} - sense mesures en les últimes {hours} h',
  'info.at': 'Posició: {name} ({id})',
  'info.model': 'Model: {model}',
  'info.by': 'Elaborat per: {who}',
  'info.windsBy': 'vents {model} de {institution}',
  'info.run': 'Execució: {date} UTC ({ago})',
  'info.runPublished': 'Execució: {date} UTC ({ago}, publicada {published})',
  'info.runNote': 'Execució: {note}',
  'info.newRunEvery': 'nova execució cada {n} h',
  'info.timeStep': 'pas de temps de {n} h',
  'info.sourceApi': "Font: {api}, a través de l'API {provider} ({host})",
  'info.sourceErddap': 'Font: ERDDAP {provider} ({host}), conjunt de dades {dataset}',
  'info.gridPoint': 'Punt de malla: {lat}° N, {lon}° E, a {km} km de la boia',
  'info.oneForecast': '1 valor de predicció, a les {time}',
  'info.forecastValues': 'Mitjana de {n} valors de predicció, {from}–{to}',
  'toast.forecast': "Aquest valor no és una mesura: prové d'una predicció de model.",
  'toast.forecastModel': "Aquest valor no és una mesura: prové d'una predicció de model ({model}).",

  'info.combined': 'Una boia combinada',
  'info.buoyCard': 'Boia',
  'info.institution': 'Institució',
  'info.position': 'Posició',
  'info.depth': 'Profunditat',
  'info.distance': 'Distància a la costa',
  'info.installed': 'Instal·lada',
  'info.lastMeasurement': 'Última mesura',
  'info.sensors': 'Sensors',
  'info.license': 'Llicència',
  'info.acknowledgement': 'Agraïments',
  'info.measurements': 'Mesures',
  'info.loading': 'Carregant…',
  'info.noMeasurements': 'sense mesures en les últimes {hours} h',
  'info.sensorShort': 'sensor {sensor}',
  'info.forecasts': 'Prediccions',
  'info.forecastsText': 'On no hi ha mesures, es mostra la predicció. Es prefereix AROME a ECMWF: '
    + 'té més resolució, però només preveu un o dos dies endavant, de manera que després pren el relleu ECMWF. '
    + "El mateix passa amb les prediccions d'onades WAVEWATCH III, que l'ICATMAR executa amb vents d'AROME i d'ECMWF. "
    + "Quan l'API d'Open-Meteo no té predicció de vent, es mostren els vents d'AROME i d'ECMWF amb què es van executar aquestes prediccions d'onades (sense ratxes). "
    + 'Les prediccions també cobreixen les hores passades (hindcast), que és el que es mostra quan una boia no té dades.',
  'info.loadingShort': 'carregant…',
  'info.noForecast': 'no hi ha cap predicció disponible per a aquesta boia',
  'info.fromTo': 'de {from} a {to}',
  'info.nearestSea': 'punt de mar més proper a {km} km',
  'info.institutions': 'Institucions',
  'join.and': ' i ',

  'role.buoy': 'boia {name}',
  'role.measurements': 'mesures ({host})',
  'role.model': '{model} ({product})',
  'role.api': 'API de predicció ({product})',
  'role.forcing': 'forçament {model} ({product})',
  'product.waves': "predicció d'onades",
  'product.wind': 'predicció de vent',
  'product.seaSurface': 'predicció de superfície marina',

  'variable.VHM0': "Alçada significant d'onada espectral (Hm0)",
  'variable.WSPD': 'Velocitat horitzontal del vent',
  'variable.TEMP': 'Temperatura del mar',
  'variable.HCSP': 'Velocitat horitzontal del corrent',

  'model.WW3-AROME': 'WAVEWATCH III forçat amb AROME',
  'model.WW3-ECMWF': 'WAVEWATCH III forçat amb ECMWF',
  'model.WW3-ECMWF-MED': 'WAVEWATCH III forçat amb ECMWF (Mediterrani)',
  'model.AROME-ERDDAP': 'AROME (forçament de WAVEWATCH III)',
  'model.ECMWF-ERDDAP': 'ECMWF (forçament de WAVEWATCH III)',
  'model.ROMS': 'Predicció de superfície marina ROMS',

  'aggregation.BCNS.description': "Les dades d'onades provenen de la boia del Port de Barcelona (PBCN, Puertos del Estado), i les de vent, temperatura de l'aigua i corrents, de la boia Somorrostro (SOMO, ICATMAR i ICM-CSIC). Les dades es combinen d'aquesta manera per la diferent disponibilitat de les dues boies: PBCN mesura onades però no vent, i SOMO mesura vent, temperatura de l'aigua i corrents però no onades.",
  'aggregation.BCNS.PBCN': 'Onades',
  'aggregation.BCNS.SOMO': "Vent, temperatura de l'aigua i corrents",

  'menu.title': 'Configuració',
  'menu.language': 'Idioma',
  'menu.units': 'Unitats',
  'menu.time': 'Hora',
  'menu.timezone': 'Zona horària',
  'menu.local': 'Local',
  'menu.utc': 'UTC',
  'menu.about': "Sobre l'aplicació",
  'menu.funding': 'Finançament',
  'about.developer': 'Aquesta aplicació està en desenvolupament i en millora constant (interfície i dades). '
    + 'Si tens cap problema o suggeriment, contacta amb Gerard Llorach-Tó ({email}).',
  'about.code': "L'aplicació és de codi obert i el codi es pot trobar a {link}.",
  'about.disclaimer': "Les dades presentades en aquesta aplicació són únicament per a fins informatius. Tot i que ens esforcem per "
    + "garantir-ne la precisió i la fiabilitat, no podem assegurar que estiguin lliures d'errors o interrupcions, i no s'han "
    + "d'utilitzar per prendre decisions crítiques sense una verificació addicional.",
  'funding.text': "Aquest treball està finançat pel Fons Europeu Marítim, de Pesca i d'Aqüicultura (FEMPA) a través de l'Institut "
    + 'Català de Recerca per a la Governança del Mar (ICATMAR) - BOE-A-2023-25106, i en el marc del projecte “Centre '
    + "d'Excel·lència Severo Ochoa”, amb el suport financer de l'ICM-CSIC (CEX2019-000928-S).",
  'logo.eu': 'Cofinançat per la Unió Europea',
};

const es = {
  'app.title': 'Boyas ICATMAR',
  'loading': 'Cargando…',
  'loading.checking': 'Comprobando las fuentes de datos…',
  'loading.ready': 'Cargando los últimos datos…',
  'loading.buoys': 'Boyas',
  'loading.forecasts': 'Predicciones',
  'loading.buoysFound': '{n} boyas',
  'loading.updatedAgo': 'actualizado {ago}',
  'loading.until': 'hasta {date}',
  'loading.unavailable': 'no disponible',
  'menu.open': 'Menú',
  'back': 'Atrás',
  'close': 'Cerrar',

  'update.loading': 'Cargando…',
  'update.updating': 'Actualizando…',
  'update.nextLabel': 'Actualización',
  'update.in': 'en {n} min',
  'update.inSoon': 'en <1 min',
  'update.refreshTitle': 'Toca para actualizar ahora',

  'column.waves': 'Oleaje',
  'column.wind': 'Viento',
  'column.temperature': 'Agua',
  'column.currents': 'Corriente',
  'header.buoy': 'Boya',
  'header.time': 'Hora',
  'header.timeTitle': 'Cambiar entre hora local y UTC',
  'header.changeUnit': 'Cambiar la unidad',
  'unit.waveHeight': 'Altura de ola',
  'unit.windSpeed': 'Velocidad del viento',
  'unit.temperature': 'Temperatura',
  'unit.waterSpeed': 'Velocidad de la corriente',
  'unitPopup.aria': 'Elige una unidad',
  'unitPopup.unit': 'Unidad',
  'unitPopup.note': 'También puedes cambiar las unidades en el menú',
  'timePopup.note': 'También puedes cambiar la zona horaria en el menú',

  'cell.maxValue': 'Máx: {value}',
  'cell.gustValue': 'Racha: {value}',
  'cell.forecastTitle': 'Predicción de modelo - toca para ver los detalles',
  'cell.measurementTitle': 'Medida - toca para ver los detalles',

  'status.loading': 'cargando…',
  'status.active': 'Activa',
  'status.delayed': 'Con retraso',
  'status.inactive': 'Inactiva',
  'ago.none': 'sin datos recientes',
  'ago.now': 'ahora',
  'ago.minutes': 'hace {n} min',
  'ago.hours': 'hace {n} h',
  'ago.days': 'hace {n} días',

  'legend.forecastList': 'Predicción de modelo (sin medidas en las últimas {hours} h)',
  'legend.forecast': 'Predicción de modelo',
  'legend.sources': 'Fuentes en el panel de información',
  'map.button': 'Mapa',
  'map.title': 'Mapa',
  'map.subtitle': 'Toca una boya para ver sus datos',

  'buoy.interval': 'Intervalo entre filas',
  'buoy.info': 'Información de la boya',

  'info.measurementAt': 'Medida de las {hour} ({from}–{to})',
  'info.buoy': 'Boya: {name} ({id})',
  'info.sensor': 'Sensor: {sensors}',
  'info.variable': 'Variable: {variables}',
  'info.publishedAs': '{code}, publicada como {raw}',
  'info.computedFrom': '{code}, calculada a partir de {raw}',
  'info.source': 'Fuente: {sources}',
  'info.oneReading': '1 lectura, a las {time}',
  'info.readings': 'Media de {n} lecturas, {from}–{to}',
  'info.forecastAt': 'Predicción de modelo de las {hour} ({from}–{to})',
  'info.forecastFor': 'Predicción de modelo para las {time} - sin medidas en las últimas {hours} h',
  'info.at': 'Posición: {name} ({id})',
  'info.model': 'Modelo: {model}',
  'info.by': 'Elaborado por: {who}',
  'info.windsBy': 'vientos {model} de {institution}',
  'info.run': 'Ejecución: {date} UTC ({ago})',
  'info.runPublished': 'Ejecución: {date} UTC ({ago}, publicada {published})',
  'info.runNote': 'Ejecución: {note}',
  'info.newRunEvery': 'nueva ejecución cada {n} h',
  'info.timeStep': 'paso de tiempo de {n} h',
  'info.sourceApi': 'Fuente: {api}, a través de la API de {provider} ({host})',
  'info.sourceErddap': 'Fuente: ERDDAP de {provider} ({host}), conjunto de datos {dataset}',
  'info.gridPoint': 'Punto de malla: {lat}° N, {lon}° E, a {km} km de la boya',
  'info.oneForecast': '1 valor de predicción, a las {time}',
  'info.forecastValues': 'Media de {n} valores de predicción, {from}–{to}',
  'toast.forecast': 'Este valor no es una medida: procede de una predicción de modelo.',
  'toast.forecastModel': 'Este valor no es una medida: procede de una predicción de modelo ({model}).',

  'info.combined': 'Una boya combinada',
  'info.buoyCard': 'Boya',
  'info.institution': 'Institución',
  'info.position': 'Posición',
  'info.depth': 'Profundidad',
  'info.distance': 'Distancia a la costa',
  'info.installed': 'Instalada',
  'info.lastMeasurement': 'Última medida',
  'info.sensors': 'Sensores',
  'info.license': 'Licencia',
  'info.acknowledgement': 'Agradecimientos',
  'info.measurements': 'Medidas',
  'info.loading': 'Cargando…',
  'info.noMeasurements': 'sin medidas en las últimas {hours} h',
  'info.sensorShort': 'sensor {sensor}',
  'info.forecasts': 'Predicciones',
  'info.forecastsText': 'Donde no hay medidas, se muestra la predicción. Se prefiere AROME a ECMWF: '
    + 'tiene más resolución, pero solo predice uno o dos días hacia delante, de modo que después toma el relevo ECMWF. '
    + 'Lo mismo ocurre con las predicciones de oleaje WAVEWATCH III, que el ICATMAR ejecuta con vientos de AROME y de ECMWF. '
    + 'Cuando la API de Open-Meteo no tiene predicción de viento, se muestran los vientos de AROME y de ECMWF con los que se ejecutaron esas predicciones de oleaje (sin rachas). '
    + 'Las predicciones también cubren las horas pasadas (hindcast), que es lo que se muestra cuando una boya no tiene datos.',
  'info.loadingShort': 'cargando…',
  'info.noForecast': 'no hay ninguna predicción disponible para esta boya',
  'info.fromTo': 'de {from} a {to}',
  'info.nearestSea': 'punto de mar más cercano a {km} km',
  'info.institutions': 'Instituciones',
  'join.and': ' y ',

  'role.buoy': 'boya {name}',
  'role.measurements': 'medidas ({host})',
  'role.model': '{model} ({product})',
  'role.api': 'API de predicción ({product})',
  'role.forcing': 'forzamiento {model} ({product})',
  'product.waves': 'predicción de oleaje',
  'product.wind': 'predicción de viento',
  'product.seaSurface': 'predicción de superficie marina',

  'variable.VHM0': 'Altura significativa de ola espectral (Hm0)',
  'variable.WSPD': 'Velocidad horizontal del viento',
  'variable.TEMP': 'Temperatura del mar',
  'variable.HCSP': 'Velocidad horizontal de la corriente',

  'model.WW3-AROME': 'WAVEWATCH III forzado con AROME',
  'model.WW3-ECMWF': 'WAVEWATCH III forzado con ECMWF',
  'model.WW3-ECMWF-MED': 'WAVEWATCH III forzado con ECMWF (Mediterráneo)',
  'model.AROME-ERDDAP': 'AROME (forzamiento de WAVEWATCH III)',
  'model.ECMWF-ERDDAP': 'ECMWF (forzamiento de WAVEWATCH III)',
  'model.ROMS': 'Predicción de superficie marina ROMS',

  'aggregation.BCNS.description': 'Los datos de oleaje proceden de la boya del Puerto de Barcelona (PBCN, Puertos del Estado), y los de viento, temperatura del agua y corrientes, de la boya Somorrostro (SOMO, ICATMAR e ICM-CSIC). Los datos se combinan de esta manera por la distinta disponibilidad de las dos boyas: PBCN mide oleaje pero no viento, y SOMO mide viento, temperatura del agua y corrientes pero no oleaje.',
  'aggregation.BCNS.PBCN': 'Oleaje',
  'aggregation.BCNS.SOMO': 'Viento, temperatura del agua y corrientes',

  'menu.title': 'Configuración',
  'menu.language': 'Idioma',
  'menu.units': 'Unidades',
  'menu.time': 'Hora',
  'menu.timezone': 'Zona horaria',
  'menu.local': 'Local',
  'menu.utc': 'UTC',
  'menu.about': 'Acerca de',
  'menu.funding': 'Financiación',
  'about.developer': 'Esta aplicación está en desarrollo y en mejora constante (interfaz y datos). '
    + 'Si tienes algún problema o sugerencia, contacta con Gerard Llorach-Tó ({email}).',
  'about.code': 'La aplicación es de código abierto y el código se puede encontrar en {link}.',
  'about.disclaimer': 'Los datos presentados en esta aplicación son únicamente informativos. Aunque nos esforzamos por garantizar '
    + 'su precisión y fiabilidad, no podemos asegurar que estén libres de errores o interrupciones, y no deben utilizarse para '
    + 'tomar decisiones críticas sin una verificación adicional.',
  'funding.text': "Este trabajo está financiado por el Fondo Europeo Marítimo, de Pesca y de Acuicultura (FEMPA) a través del "
    + 'Instituto Catalán de Investigación para la Gobernanza del Mar (ICATMAR) - BOE-A-2023-25106, y en el marco del proyecto '
    + '“Centro de Excelencia Severo Ochoa”, con el apoyo financiero del ICM-CSIC (CEX2019-000928-S).',
  'logo.eu': 'Cofinanciado por la Unión Europea',
};

const fr = {
  'app.title': 'Bouées ICATMAR',
  'loading': 'Chargement…',
  'loading.checking': 'Vérification des sources de données…',
  'loading.ready': 'Chargement des dernières données…',
  'loading.buoys': 'Bouées',
  'loading.forecasts': 'Prévisions',
  'loading.buoysFound': '{n} bouées',
  'loading.updatedAgo': 'mis à jour {ago}',
  'loading.until': "jusqu'à {date}",
  'loading.unavailable': 'non disponible',
  'menu.open': 'Menu',
  'back': 'Retour',
  'close': 'Fermer',

  'update.loading': 'Chargement…',
  'update.updating': 'Mise à jour…',
  'update.nextLabel': 'Mise à jour',
  'update.in': 'dans {n} min',
  'update.inSoon': 'dans <1 min',
  'update.refreshTitle': 'Touchez pour mettre à jour maintenant',

  'column.waves': 'Vagues',
  'column.wind': 'Vent',
  'column.temperature': 'Eau',
  'column.currents': 'Courant',
  'header.buoy': 'Bouée',
  'header.time': 'Heure',
  'header.timeTitle': "Basculer entre l'heure locale et UTC",
  'header.changeUnit': "Changer l'unité",
  'unit.waveHeight': 'Hauteur des vagues',
  'unit.windSpeed': 'Vitesse du vent',
  'unit.temperature': 'Température',
  'unit.waterSpeed': 'Vitesse du courant',
  'unitPopup.aria': 'Choisir une unité',
  'unitPopup.unit': 'Unité',
  'unitPopup.note': 'Les unités peuvent aussi être changées dans le menu',
  'timePopup.note': 'Le fuseau horaire peut aussi être changé dans le menu',

  'cell.maxValue': 'Max : {value}',
  'cell.gustValue': 'Rafale : {value}',
  'cell.forecastTitle': 'Prévision de modèle - touchez pour voir les détails',
  'cell.measurementTitle': 'Mesure - touchez pour voir les détails',

  'status.loading': 'chargement…',
  'status.active': 'Active',
  'status.delayed': 'En retard',
  'status.inactive': 'Inactive',
  'ago.none': 'pas de données récentes',
  'ago.now': 'maintenant',
  'ago.minutes': 'il y a {n} min',
  'ago.hours': 'il y a {n} h',
  'ago.days': 'il y a {n} jours',

  'legend.forecastList': 'Prévision de modèle (aucune mesure depuis {hours} h)',
  'legend.forecast': 'Prévision de modèle',
  'legend.sources': "Sources dans le panneau d'information",
  'map.button': 'Carte',
  'map.title': 'Carte',
  'map.subtitle': 'Touchez une bouée pour voir ses données',

  'buoy.interval': 'Intervalle entre les lignes',
  'buoy.info': 'Informations sur la bouée',

  'info.measurementAt': 'Mesure de {hour} ({from}–{to})',
  'info.buoy': 'Bouée : {name} ({id})',
  'info.sensor': 'Capteur : {sensors}',
  'info.variable': 'Variable : {variables}',
  'info.publishedAs': '{code}, publiée sous le nom {raw}',
  'info.computedFrom': '{code}, calculée à partir de {raw}',
  'info.source': 'Source : {sources}',
  'info.oneReading': '1 mesure, à {time}',
  'info.readings': 'Moyenne de {n} mesures, {from}–{to}',
  'info.forecastAt': 'Prévision de modèle de {hour} ({from}–{to})',
  'info.forecastFor': 'Prévision de modèle pour {time} - aucune mesure depuis {hours} h',
  'info.at': 'Position : {name} ({id})',
  'info.model': 'Modèle : {model}',
  'info.by': 'Produit par : {who}',
  'info.windsBy': 'vents {model} de {institution}',
  'info.run': 'Run : {date} UTC ({ago})',
  'info.runPublished': 'Run : {date} UTC ({ago}, publié {published})',
  'info.runNote': 'Run : {note}',
  'info.newRunEvery': 'nouveau run toutes les {n} h',
  'info.timeStep': 'pas de temps de {n} h',
  'info.sourceApi': "Source : {api}, via l'API {provider} ({host})",
  'info.sourceErddap': 'Source : ERDDAP {provider} ({host}), jeu de données {dataset}',
  'info.gridPoint': 'Point de grille : {lat}° N, {lon}° E, à {km} km de la bouée',
  'info.oneForecast': '1 valeur de prévision, à {time}',
  'info.forecastValues': 'Moyenne de {n} valeurs de prévision, {from}–{to}',
  'toast.forecast': "Cette valeur n'est pas une mesure : elle provient d'une prévision de modèle.",
  'toast.forecastModel': "Cette valeur n'est pas une mesure : elle provient d'une prévision de modèle ({model}).",

  'info.combined': 'Une bouée combinée',
  'info.buoyCard': 'Bouée',
  'info.institution': 'Institution',
  'info.position': 'Position',
  'info.depth': 'Profondeur',
  'info.distance': 'Distance à la côte',
  'info.installed': 'Installée',
  'info.lastMeasurement': 'Dernière mesure',
  'info.sensors': 'Capteurs',
  'info.license': 'Licence',
  'info.acknowledgement': 'Remerciements',
  'info.measurements': 'Mesures',
  'info.loading': 'Chargement…',
  'info.noMeasurements': 'aucune mesure depuis {hours} h',
  'info.sensorShort': 'capteur {sensor}',
  'info.forecasts': 'Prévisions',
  'info.forecastsText': "Là où il n'y a pas de mesures, la prévision est affichée à la place. AROME est préféré à ECMWF : "
    + "sa résolution est plus élevée, mais il ne prévoit qu'un ou deux jours à l'avance, ECMWF prend donc le relais ensuite. "
    + "Il en va de même pour les prévisions de vagues WAVEWATCH III, exécutées par l'ICATMAR avec les vents d'AROME et d'ECMWF. "
    + "Lorsque l'API Open-Meteo n'a pas de prévision de vent, ce sont les vents d'AROME et d'ECMWF utilisés pour ces prévisions de vagues qui sont affichés (sans rafales). "
    + "Les prévisions couvrent aussi les heures passées (hindcast), ce qui est affiché lorsqu'une bouée n'a pas de données.",
  'info.loadingShort': 'chargement…',
  'info.noForecast': "aucune prévision n'est disponible pour cette bouée",
  'info.fromTo': 'du {from} au {to}',
  'info.nearestSea': 'point de mer le plus proche à {km} km',
  'info.institutions': 'Institutions',
  'join.and': ' et ',

  'role.buoy': 'bouée {name}',
  'role.measurements': 'mesures ({host})',
  'role.model': '{model} ({product})',
  'role.api': 'API de prévision ({product})',
  'role.forcing': 'forçage {model} ({product})',
  'product.waves': 'prévision de vagues',
  'product.wind': 'prévision de vent',
  'product.seaSurface': 'prévision de surface de la mer',

  'variable.VHM0': 'Hauteur significative spectrale des vagues (Hm0)',
  'variable.WSPD': 'Vitesse horizontale du vent',
  'variable.TEMP': 'Température de la mer',
  'variable.HCSP': 'Vitesse horizontale du courant',

  'model.WW3-AROME': 'WAVEWATCH III forcé par AROME',
  'model.WW3-ECMWF': 'WAVEWATCH III forcé par ECMWF',
  'model.WW3-ECMWF-MED': 'WAVEWATCH III forcé par ECMWF (Méditerranée)',
  'model.AROME-ERDDAP': 'AROME (forçage de WAVEWATCH III)',
  'model.ECMWF-ERDDAP': 'ECMWF (forçage de WAVEWATCH III)',
  'model.ROMS': 'Prévision de surface de la mer ROMS',

  'aggregation.BCNS.description': "Les données de vagues proviennent de la bouée du Port de Barcelone (PBCN, Puertos del Estado), et celles de vent, de température de l'eau et de courants, de la bouée Somorrostro (SOMO, ICATMAR et ICM-CSIC). Les données sont combinées ainsi en raison de la disponibilité différente des deux bouées : PBCN mesure les vagues mais pas le vent, et SOMO mesure le vent, la température de l'eau et les courants mais pas les vagues.",
  'aggregation.BCNS.PBCN': 'Vagues',
  'aggregation.BCNS.SOMO': "Vent, température de l'eau et courants",

  'menu.title': 'Paramètres',
  'menu.language': 'Langue',
  'menu.units': 'Unités',
  'menu.time': 'Heure',
  'menu.timezone': 'Fuseau horaire',
  'menu.local': 'Locale',
  'menu.utc': 'UTC',
  'menu.about': 'À propos',
  'menu.funding': 'Financement',
  'about.developer': "Cette application est en développement et en amélioration constante (interface et données). "
    + "Si vous rencontrez un problème ou avez des suggestions, contactez Gerard Llorach-Tó ({email}).",
  'about.code': "L'application est open source et le code est disponible sur {link}.",
  'about.disclaimer': "Les données présentées dans cette application sont fournies à titre informatif uniquement. Bien que nous nous "
    + "efforcions d'en garantir l'exactitude et la fiabilité, nous ne pouvons pas assurer qu'elles soient exemptes d'erreurs ou "
    + "d'interruptions, et elles ne doivent pas être utilisées pour prendre des décisions critiques sans vérification supplémentaire.",
  'funding.text': "Ce travail est financé par le Fonds européen pour les affaires maritimes, la pêche et l'aquaculture (FEAMPA) via "
    + "l'Institut catalan de recherche pour la gouvernance de la mer (ICATMAR) - BOE-A-2023-25106, et dans le cadre du projet "
    + "« Centre d'excellence Severo Ochoa », avec le soutien financier de l'ICM-CSIC (CEX2019-000928-S).",
  'logo.eu': "Cofinancé par l'Union européenne",
};

// In the order the menu offers them, with the locale each one formats dates in
const LANGUAGES = {
  ca: { name: 'Català', locale: 'ca-ES', texts: ca },
  es: { name: 'Español', locale: 'es-ES', texts: es },
  fr: { name: 'Français', locale: 'fr-FR', texts: fr },
  en: { name: 'English', locale: 'en-GB', texts: en },
};

export default LANGUAGES;
